# Generated by Django 3.2.13 on 2023-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20230124_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
